---
- hosts: webs
  roles:
    - { role: geerlingguy.nginx }
  vars:
    nginx_vhosts:
    - listen: "443 ssl http2"
      server_name: "edu.lan"
      server_name_redirect: "www.edu.lan"
      root: "/var/www/html/edu.lan"
      index: "index.php index.html index.htm"
      access_log: "/var/log/nginx/edu.lan_access.log"
      error_log: "/var/log/nginx/edu.lan_error.log"
      state: "present"
      template: "{{ nginx_vhost_template }}"
      filename: "edu.lan.conf"
      extra_parameters: |
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        ssl_certificate     /etc/pki/tls/certs/edu.lan.crt;
        ssl_certificate_key /etc/pki/tls/private/edu.lan.key;
        ssl_protocols       TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;
    - listen: "80"
      server_name: "edu.lan www.edu.lan"
      return: "301 https://edu.lan$request_uri"
      filename: "edu.lan.80.conf"

    - listen: "443 ssl http2"
      server_name: "class.net"
      server_name_redirect: "www.class.net"
      root: "/var/www/html/class.net"
      index: "index.php index.html index.htm"
      access_log: "/var/log/nginx/class.net_access.log"
      error_log: "/var/log/nginx/class.net_error.log"
      state: "present"
      template: "{{ nginx_vhost_template }}"
      filename: "class.net.conf"
      extra_parameters: |
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        ssl_certificate     /etc/pki/tls/certs/edu.lan.crt;
        ssl_certificate_key /etc/pki/tls/private/edu.lan.key;
        ssl_protocols       TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;
    - listen: "80"
      server_name: "class.net www.class.net"
      return: "301 https://class.net$request_uri"
      filename: "class.net.80.conf"

